// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PetCheckTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void petCheck() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    driver.FindElement(By.CssSelector("li:nth-child(5) span:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(5) span:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".addSpecialty")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".addSpecialty"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("equine heart surgeon");
    driver.FindElement(By.CssSelector(".btn:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".addPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("equine");
    driver.FindElement(By.CssSelector(".saveType")).Click();
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) > a")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Joe");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Joshovich");
    driver.FindElement(By.Id("specialties")).Click();
    {
      var dropdown = driver.FindElement(By.Id("specialties"));
      dropdown.FindElement(By.XPath("//option[. = 'equine heart surgeon']")).Click();
    }
    driver.FindElement(By.CssSelector(".saveVet")).Click();
    driver.FindElement(By.CssSelector(".ownerTab > .caret")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.LinkText("Max Nov")).Click();
    driver.FindElement(By.CssSelector(".addNewPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Steak");
    driver.FindElement(By.Name("birthDate")).Click();
    {
      var element = driver.FindElement(By.CssSelector("path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("path")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(1) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'equine']")).Click();
    }
    driver.FindElement(By.CssSelector(".savePet")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(5) span:nth-child(2)")).Click();
    {
      string value = driver.FindElement(By.Id("11")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("equine heart surgeon"));
    }
    driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)")).Click();
    {
      string value = driver.FindElement(By.Id("40")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("equine"));
    }
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td)[82]")).Text, Is.EqualTo("Joe Joshovich"));
    driver.FindElement(By.CssSelector(".ownerTab > .caret")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.LinkText("Max Nov")).Text, Is.EqualTo("Max Nov"));
  }
}
